---
title: "Strings and Factors"
author: Selina Lyu
output: github_document
---

```{r, include = FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Strings

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff") #detect a particular pattern, does this appear in my string
str_detect(string_vec, "Jeff")
str_detect(string_vec, "e")

str_replace(string_vec, "jeff", "Jeff")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think") #all true
str_detect(string_vec, "^i think") #start with i think
str_detect(string_vec, "i think$") #end with i think
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin") #match either B or b --> Pumpkin and pumpkin both
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]") #a number first, followed immediately by a letter
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # "." is a function means a special character that matches any symbol

str_detect(string_vec, "7\\.11") # only 7.11 is detected
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") #only [ is detected
```

## Factors

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex #female is the first category --> alphabetical

as.numeric(vec_sex) # 2 2 1 1
```

what happens if I relevel...
```{r}
vec_sex = fct_relevel(vec_sex, "male")
vec_sex

as.numeric(vec_sex) # 1 1 2 2
```

## NSDUH -- strings
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |>
  slice(-1) |>
  as_tibble()
```

```{r}
data_marj =
  table_marj |>
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)
  ) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

## NSDUH -- factors

```{r}
data_marj |>
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> #appear according to prevalence
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

data_marj |>
  filter(age == "12-17") |> 
  mutate(State = fct_relevel(State, "Texas")) |> # changing "State" from chr to fct variable, also set Texas as default state
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) #Texas is the first state
```

## Weather data

```{r}
library(p8105.datasets)
data("weather_df")

weather_df |>
  mutate(name = forcats::fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")

weather_df |>
  mutate(name = forcats::fct_reorder(name, tmax)) |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```

```{r}
weather_df |>
  lm(tmax ~ name, data = _)
```
linear regression --> central park is the reference group

```{r}
weather_df |>
  mutate(name = forcats::fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> 
  lm(tmax ~ name, data = _)
```







